"""LLM-as-Judge evaluation with five-dimensional meteorological scoring."""
from __future__ import annotations

import argparse
import json
import logging
import os
import re
from pathlib import Path
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from openai import OpenAI

logger = logging.getLogger(__name__)

DEFAULT_BASE_URL = os.environ.get("LLM_BASE_URL", "")
DEFAULT_API_KEY = os.environ.get("LLM_API_KEY", "EMPTY")
DEFAULT_MODEL = os.environ.get("LLM_MODEL", "deepseekr1")

_PROMPT_TEMPLATE = """You are an expert meteorological evaluator. Your task is to evaluate a weather forecast generated by an AI assistant by comparing it with the human-annotated reference forecast.

# Background Knowledge Base
江南：包括江苏南部（苏南）、浙江、上海、安徽南部（皖南）、江西北部、湖南北部等区域。
华南：包括广东省、广西壮族自治区、海南省、香港、澳门。
淮南：指淮河以南地区，主要包括安徽中部、江苏中部和河南南部。
东北：指辽宁省、吉林省、黑龙江省以及内蒙古自治区东部。
江汉：指湖北省中南部的江汉平原。
江淮：指长江与淮河之间的区域，主要包括安徽中部和江苏中部。
黄淮：指黄河与淮河之间的区域，包括河南东部、安徽北部、山东西南部、江苏北部。
华北：包括北京市、天津市、河北省、山西省、内蒙古自治区。
新疆伊犁河谷：位于新疆西部天山山脉内的河谷地带。
内蒙古河套地区：位于内蒙古黄河“几”字弯顶部的平原地区。

AI assistant's forecast:
{assistant_answer}

Human reference forecast:
{human_answer}

Evaluate the AI forecast according to the following indicators:
1. Time Accuracy (1-10)
- Description: Does the forecast describe the correct time range as in the reference?
- Scoring: Deduct points for incorrect or missing dates/times.
2. Region Accuracy (1-10)
- Description: Are all mentioned regions correct, without extra unrelated regions?
- Scoring: Use the background knowledge base to verify if named large regions correctly match their constituent provinces.
3. Weather Phenomena Accuracy (1-10)
- Description: Are rainfall levels (light, moderate, heavy rain, torrential rain, etc.) and wind strengths (e.g., 4-6 grade winds) correctly matched to the right regions?
- Scoring: Deduct points for mismatched intensities or incorrect weather types.
4. Completeness (1-10)
- Description: Does the AI forecast include all key events and regions mentioned in the human reference?
- Scoring: Deduct points for missing important weather phenomena or locations.
5. No Hallucination (1-10)
- Description: The forecast should not add new events, regions, or phenomena that are not in the reference.
- Scoring: Deduct heavily for invented or unrelated information.

Scoring Rule: Each indicator is scored from 1 (very poor) to 10 (perfect).
Final Score = Weighted Average: Time Accuracy 15%, Region Accuracy 25%, Weather Phenomena Accuracy 25%, Completeness 20%, No Hallucination 15%.

Output Format: Must return a strict JSON object containing only the following key-value pairs, with numeric values:
{{"time_accuracy": 1.0, "region_accuracy": 1.0, "weather_phenomena_accuracy": 1.0, "completeness": 1.0, "no_hallucination": 1.0, "total_score": 1.0}}

Notes:
1. Output strictly according to the JSON structure above, without adding any additional text, explanations, or descriptions.
2. All values must be in the range of 1.0-10.0, with one decimal place.
3. total_score must be calculated according to the weighted formula and must be logically consistent with each indicator score.
"""

REQUIRED_SCORE_FIELDS = (
    "time_accuracy",
    "region_accuracy",
    "weather_phenomena_accuracy",
    "completeness",
    "no_hallucination",
)

SCORE_WEIGHTS = {
    "time_accuracy": 0.15,
    "region_accuracy": 0.25,
    "weather_phenomena_accuracy": 0.25,
    "completeness": 0.20,
    "no_hallucination": 0.15,
}


def calculate_total_score(scores: dict[str, float]) -> float:
    """Calculate the weighted total score defined in the MetServ-VL paper."""
    return round(sum(scores[field] * weight for field, weight in SCORE_WEIGHTS.items()), 2)


def normalize_scores(scores: dict[str, Any]) -> dict[str, float] | None:
    """Validate score fields and recompute ``total_score`` for consistency."""
    normalized: dict[str, float] = {}
    for field in REQUIRED_SCORE_FIELDS:
        try:
            value = float(scores[field])
        except (KeyError, TypeError, ValueError):
            return None
        normalized[field] = max(1.0, min(10.0, round(value, 1)))
    normalized["total_score"] = calculate_total_score(normalized)
    return normalized


def extract_scores(text: str) -> dict[str, float] | None:
    """Extract JSON scores from LLM response text using regex.

    Args:
        text: Raw LLM output.

    Returns:
        Dictionary of scores, or ``None`` if extraction fails.
    """
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL | re.IGNORECASE)
    try:
        decoder = json.JSONDecoder()
        for match in re.finditer(r"\{", text):
            try:
                parsed, _ = decoder.raw_decode(text[match.start():])
            except json.JSONDecodeError:
                continue
            if isinstance(parsed, dict):
                normalized = normalize_scores(parsed)
                if normalized is not None:
                    return normalized
    except (json.JSONDecodeError, Exception):
        pass

    # Fallback: extract individual fields
    scores: dict[str, Any] = {}
    for field in REQUIRED_SCORE_FIELDS:
        m = re.search(rf'"{field}":\s*([\d.]+)', text)
        if m:
            scores[field] = float(m.group(1))
    return normalize_scores(scores) if scores else None


def evaluate_forecast(
    json_path: str | Path,
    save_path: str | Path,
    client: "OpenAI",
    model_name: str,
) -> None:
    """Evaluate all entries in a JSON file and save scored results.

    Args:
        json_path: Input JSON file with human/assistant answers.
        save_path: Output path for scored JSON.
        client: OpenAI-compatible client.
        model_name: Model identifier for evaluation.
    """
    data = json.loads(Path(json_path).read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("Input JSON root must be a list")

    for i, item in enumerate(data):
        if "assistant_answer" not in item or "human_answer" not in item:
            logger.warning("Item %d missing required fields; skipping", i)
            continue

        prompt = _PROMPT_TEMPLATE.format(
            assistant_answer=item["assistant_answer"],
            human_answer=item["human_answer"],
        )
        try:
            response = client.chat.completions.create(
                model=model_name,
                messages=[{"role": "system", "content": prompt}],
                temperature=0.1,
                max_tokens=2048,
            )
        except Exception as exc:
            logger.error("Item %d API call failed: %s", i, exc)
            item["scores"] = {"error": f"API error: {exc}"}
            continue

        text = response.choices[0].message.content.strip()
        score_data = extract_scores(text)

        if score_data:
            item["scores"] = score_data
            logger.info("Item %d scored: %.2f", i, score_data.get("total_score", 0))
        else:
            item["scores"] = {"error": "Incomplete scores", "raw_response": text}
            logger.warning("Item %d score extraction failed", i)

    Path(save_path).parent.mkdir(parents=True, exist_ok=True)
    Path(save_path).write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    logger.info("Scored results saved to %s", save_path)


def main() -> None:
    parser = argparse.ArgumentParser(description="LLM-as-Judge meteorological evaluation")
    parser.add_argument("--input", type=str, required=True, help="Input JSON file")
    parser.add_argument("--output", type=str, required=True, help="Output JSON file")
    parser.add_argument("--base_url", type=str, default=DEFAULT_BASE_URL, help="API base URL")
    parser.add_argument("--api_key", type=str, default=DEFAULT_API_KEY, help="API key")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help="Judge model name")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    if not args.base_url:
        logger.error("LLM_BASE_URL not set. Provide --base_url or set env var.")
        raise SystemExit(1)

    try:
        from openai import OpenAI
    except ImportError as exc:
        logger.error("openai package is required for LLM-as-Judge evaluation: %s", exc)
        raise SystemExit(1) from exc

    client = OpenAI(base_url=args.base_url, api_key=args.api_key)
    evaluate_forecast(args.input, args.output, client, args.model)


if __name__ == "__main__":
    main()
